% Loads the following constants in the Workspace 
% 
% AU            astronomical unit [km]
% D_sideral     length of sideral day [s]
% i_Delfi       inclination orbit Delfi-C3 [deg]
% i_ENVISAT     inclination orbit ENVISAT [deg]
% i_GPS         inclination orbit GPS [deg]
% i_ISS         inclination orbit International Space Station [deg]
% J_2           J_2 coefficient gravity field Earth [-]
% J_22          J_{2,2} coefficient gravity field Earth [-]
% R_E           radius Earth [km]
% R_J           radius Jupiter [km]
% R_M           radius Mars [km]
% R_S           radius Sun [km]
% r_J           distance Sun-Jupiter [km]
% r_M           distance Sun-Mars [km]
% SC            solar constant [W*m^-2]
% lat_Baikonur  latitude Baikonur [deg]
% lat_Delft     latitude Delft [deg]
% lat_KSC       latitude Kennedy Space Center [deg]
% lat_Plesetsk  latitude Plesetsk [deg]
% lon_Delft     longitude Delft [deg]
% lambda_22     \lambda_{2,2} coef. gravity field Earth [deg]
% mu_E          gravitational parameter Earth [km^3*s^-2]
% mu_J          gravitational parameter Jupiter [km^3*s^-2]
% mu_M          gravitational parameter Mars [km^3*s^-2]
% mu_S          gravitational parameter Sun [km^3*s^-2]

AU = 149597870.66; % astronomical unit [km]
D_sideral = 86164.1004; % length of sideral day [s]
i_Delfi = 98; % inclination orbit Delfi-C3 [deg]
i_ENVISAT = 98.5; % inclination orbit ENVISAT [deg]
i_GPS = 55.0; % inclination orbit GPS [deg]
i_ISS = 51.9; % inclination orbit International Space Station [deg]
J_2 = 1082.63e-6; % J_2 coefficient gravity field Earth [-]
J_22 = 1.82e-6; % J_{2,2} coefficient gravity field Earth [-]
R_E = 6378.136; % radius Earth [km]
R_J = 71492; % radius Jupiter [km]
R_M = 3397; % radius Mars [km]
R_S = 6.96033e5; % radius Sun [km]
r_J = 5.20336301; % distance Sun-Jupiter [km]
r_M = 1.52366231; % distance Sun-Mars [km]
SC = 1367; % solar constant [W*m^-2]
lat_Baikonur = 45.6; % latitude Baikonur [deg]
lat_Delft = 52.0; % latitude Delft [deg]
lat_KSC = 28.5; % latitude Kennedy Space Center [deg]
lat_Plesetsk = 62.8; % latitude Plesetsk [deg]
lon_Delft = 4.3; % longitude Delft [deg]
lambda_22 = -14.9; % \lambda_{2,2} coef. gravity field Earth [deg]
mu_E = 398600.441; % gravitational parameter Earth [km^3*s^-2]
mu_J = 1.2669e8; % gravitational parameter Jupiter [km^3*s^-2]
mu_M = 4.2832e4; % gravitational parameter Mars [km^3*s^-2]
mu_S = 1.327178e11; % gravitational parameter Sun [km^3*s^-2]
